AWSTemplateFormatVersion: '2010-09-09'
Description: 'Adds S3 permissions to existing OIDC role for Terraform state management'

Parameters:
  OIDCRoleArn:
    Type: String
    Description: ARN of the existing OIDC role
    
  StateBucketName:
    Type: String
    Description: Name of the Terraform state bucket

Resources:
  TerraformStatePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TerraformStateAccess
      Roles: 
        - !Select [1, !Split ['/', !Ref OIDCRoleArn]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:GetObjectVersion'
              - 's3:GetBucketVersioning'
              - 's3:PutObjectRetention'
              - 's3:GetObjectRetention'
              - 's3:PutObjectLegalHold'
              - 's3:GetObjectLegalHold'
            Resource:
              - !Sub 'arn:aws:s3:::${StateBucketName}'
              - !Sub 'arn:aws:s3:::${StateBucketName}/*'
