name: Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - 'aws_infrastructure/**'
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: aws_infrastructure/terraform

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      dev1_repo: ${{ steps.tf-output.outputs.dev1_repo }}
      grafana_repo: ${{ steps.tf-output.outputs.grafana_repo }}
      influxdb_repo: ${{ steps.tf-output.outputs.influxdb_repo }}
      nodered_repo: ${{ steps.tf-output.outputs.nodered_repo }}
      postgres_repo: ${{ steps.tf-output.outputs.postgres_repo }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve

    - name: Get Terraform Outputs
      id: tf-output
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: |
        echo "dev1_repo=$(terraform output -raw 'repository_urls.dev1')" >> $GITHUB_OUTPUT
        echo "grafana_repo=$(terraform output -raw 'repository_urls.grafana')" >> $GITHUB_OUTPUT
        echo "influxdb_repo=$(terraform output -raw 'repository_urls.influxdb')" >> $GITHUB_OUTPUT
        echo "nodered_repo=$(terraform output -raw 'repository_urls.nodered')" >> $GITHUB_OUTPUT
        echo "postgres_repo=$(terraform output -raw 'repository_urls.postgres')" >> $GITHUB_OUTPUT

  build-and-push:
    needs: terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push images
      env:
        DEV1_REPO: ${{ needs.terraform.outputs.dev1_repo }}
        GRAFANA_REPO: ${{ needs.terraform.outputs.grafana_repo }}
        INFLUXDB_REPO: ${{ needs.terraform.outputs.influxdb_repo }}
        NODERED_REPO: ${{ needs.terraform.outputs.nodered_repo }}
        POSTGRES_REPO: ${{ needs.terraform.outputs.postgres_repo }}
      run: |
        services=("dev1" "nodered" "influxdb" "grafana" "postgres")
        
        for service in "${services[@]}"; do
          if [ -d "infrastructure/${service}" ]; then
            echo "Building ${service}..."
            case $service in
              "dev1")
                repo_url=$DEV1_REPO
                ;;
              "grafana")
                repo_url=$GRAFANA_REPO
                ;;
              "influxdb")
                repo_url=$INFLUXDB_REPO
                ;;
              "nodered")
                repo_url=$NODERED_REPO
                ;;
              "postgres")
                repo_url=$POSTGRES_REPO
                ;;
            esac
            
            docker build -t ${repo_url}:latest infrastructure/${service}/
            docker push ${repo_url}:latest
            echo "Pushed ${service} to ECR"
          else
            echo "Directory infrastructure/${service} not found, skipping..."
          fi
        done
